### ISSUE TITLE
New versions of beautifulsoup4 fail

### ISSUE THREAD

**Issue by fracpete** [fracpete/kodi-nfo-generator#2]
Fails: beautifulsoup4==4.9.3
Works: beautifulsoup4==4.6.0

Investigate reason of failure.

**Comment by fracpete** [comment]
Error message:
```
INFO:kodi.generator:Traceback (most recent call last):
  File "/home/fracpete/temp/nfo/venv/lib/python3.7/site-packages/kodi/generator.py", line 91, in generate
    nfo_file=xml_path)
  File "/home/fracpete/temp/nfo/venv/lib/python3.7/site-packages/kodi/imdb.py", line 71, in generate_imdb
    j = json.loads(script.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by fracpete** [comment]
Working versions of beautifulsoup4: 
- 4.6.3
- 4.7.1
- 4.8.2
- 4.10.0

Hence excluding 4.9.x in `setup.py` (97fc7dea9951e42417bc3213359dba40b19629d6).
