### ISSUE TITLE
Problem generate nfo for episodes

### ISSUE THREAD

**Issue by Chronosaurus42** [fracpete/kodi-nfo-generator#7]
Hi, i try to generate a nfo file for episodes, but it does not work, tested with python3.8 and 3.11 - same problem.

```
➤ kodi-nfo-gen --dir ~/spinningDisk1/Wer\ nicht\ fragt,\ stirbt\ dumm!\ \(2015\)/ --episodes --verbose --debug --overwrite                                                                                                      20:14:56
DEBUG:kodi.generator:Namespace(dir='/home/karloff/spinningDisk1/Wer nicht fragt, stirbt dumm! (2015)/', type='imdb', recursive=False, pattern='*.imdb', delay=1, language='en', fanart='none', fanart_file='folder.jpg', episodes=True, episode_pattern='*S??E??*.*', season_group='.*S([0-9]?[0-9])E.*', episode_group='.*E([0-9]?[0-9]).*', dry_run=False, overwrite=True, verbose=True, debug=True, interactive=False, user_agent='Mozilla')
INFO:kodi.generator:# dirs: 1
INFO:kodi.generator:Current dir: /home/karloff/spinningDisk1/Wer nicht fragt, stirbt dumm! (2015)/
INFO:kodi.generator:ID file: /home/karloff/spinningDisk1/Wer nicht fragt, stirbt dumm! (2015)/Wer nicht fragt, stirbt dumm!.imdb
INFO:kodi.generator:ID: tt5338680
INFO:kodi.imdb:IMDB URL: https://www.imdb.com/title/tt5338680/
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.imdb.com:443
DEBUG:urllib3.connectionpool:https://www.imdb.com:443 "GET /title/tt5338680/ HTTP/1.1" 200 None
DEBUG:kodi.imdb:{'@context': 'https://schema.org', '@type': 'TVSeries', 'url': 'https://www.imdb.com/title/tt5338680/', 'name': 'Tu mourras moins bête', 'image': 'https://m.media-amazon.com/images/M/MV5BNzZlNTQ2ODgtYzQ1YS00MzNiLWIxNDEtNTI2ODA0MTU2MWU2XkEyXkFqcGdeQXVyMjU1ODAyMDM@._V1_.jpg', 'description': 'A mustached female professor answers scientific questions in a comedic way, for multiple customers.', 'aggregateRating': {'@type': 'AggregateRating', 'ratingCount': 48, 'bestRating': 10, 'worstRating': 1, 'ratingValue': 7.9}, 'genre': ['Animation', 'Short', 'Comedy'], 'datePublished': '2015-08-23', 'keywords': 'question,scientific explanation,question and answer,scientist,science', 'actor': [{'@type': 'Person', 'url': 'https://www.imdb.com/name/nm0603586/', 'name': 'François Morel'}, {'@type': 'Person', 'url': 'https://www.imdb.com/name/nm1767399/', 'name': 'Jérôme Pauwels'}, {'@type': 'Person', 'url': 'https://www.imdb.com/name/nm0287131/', 'name': 'Nathalie Fort'}], 'creator': [{'@type': 'Organization', 'url': 'https://www.imdb.com/company/co0044919/'}, {'@type': 'Organization', 'url': 'https://www.imdb.com/company/co0028384/'}, {'@type': 'Organization', 'url': 'https://www.imdb.com/company/co0014456/'}]}
INFO:kodi.imdb:Has episode data
INFO:kodi.imdb:Default episodes URL: https://www.imdb.com/title/tt5338680/episodes/
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.imdb.com:443
DEBUG:urllib3.connectionpool:https://www.imdb.com:443 "GET /title/tt5338680/episodes/ HTTP/1.1" 200 None
INFO:kodi.imdb:Season using buttons
INFO:kodi.imdb:Available seasons:
INFO:kodi.imdb:Located seasons: 1, 2, 3
INFO:kodi.imdb:Season 1 URL: https://www.imdb.com/title/tt5338680/episodes/?season=1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.imdb.com:443
DEBUG:urllib3.connectionpool:https://www.imdb.com:443 "GET /title/tt5338680/episodes/?season=1 HTTP/1.1" 200 None
INFO:kodi.imdb:extract_episodes: episode-item-wrapper based
INFO:kodi.generator:Traceback (most recent call last):
  File "/home/karloff/pip/kodi-nfo-gen/lib/python3.11/site-packages/kodi/generator.py", line 98, in generate
    file_generated = generate_imdb(id, language=language, fanart=fanart, fanart_file=fanart_file,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karloff/pip/kodi-nfo-gen/lib/python3.11/site-packages/kodi/imdb.py", line 211, in generate_imdb
    episodes_data = extract_episodes(soup_ep, season)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karloff/pip/kodi-nfo-gen/lib/python3.11/site-packages/kodi/imdb_series.py", line 236, in extract_episodes
    s = rating_tag["aria-label"]
        ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/karloff/pip/kodi-nfo-gen/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'aria-label'
```

my files order in following schema

```
➤ ls -1 ~/spinningDisk1/Wer\ nicht\ fragt,\ stirbt\ dumm!\ \(2015\)/                                                                                                                                         20:22:21
'S01E01 - Wer_nicht_fragt,_stirbt_dumm!_-_Angst_vorm_Fliegen.mp4'
'S01E02 - Wer_nicht_fragt,_stirbt_dumm!_-_Liebling,_ich_will_die_Kinder_schrumpfen!.mp4'
'S01E03 - Wer_nicht_fragt,_stirbt_dumm!_-_Wann_kommt_das_Laserschwert?.mp4'
'S01E04 - Wer_nicht_fragt,_stirbt_dumm!_-_Der_Sprung_von_der_Golden_Gate_Bridge.mp4'
'S01E05 - Wer_nicht_fragt,_stirbt_dumm!_-_Immunologie.mp4'
'S01E06 - Wer_nicht_fragt,_stirbt_dumm!_-_Im_Schlaf_Spinnen_verschlucken.mp4'
'S01E07 - Wer_nicht_fragt,_stirbt_dumm!_-_Kopfverpflanzungen.mp4'
'S01E08 - Wer_nicht_fragt,_stirbt_dumm!_-_Einführung_in_die_Hobbitologie.mp4'
'S01E09 - Wer_nicht_fragt,_stirbt_dumm!_-_Meine_Freundin_liebt_ein_Pony.mp4'
'S01E10 - Wer_nicht_fragt,_stirbt_dumm!_-_Higgs-Boson?_Wassolldassein?.mp4'
'S01E11 - Wer_nicht_fragt,_stirbt_dumm!_-_Wann_kommt_die_Kryonik?.mp4'
'S01E12 - Wer_nicht_fragt,_stirbt_dumm!_-_Wie_Tiere_die_Welt_sehen.mp4'
[...]
'S03E27 - Wer_nicht_fragt,_stirbt_dumm!_-_Atomversuch_mit_Ziege.mp4'
'S03E28 - Wer_nicht_fragt,_stirbt_dumm!_-_Was_sind_Pseudowissenschaften?.mp4'
'S03E29 - Wer_nicht_fragt,_stirbt_dumm!_-_Wie_verläuft_ein_wissenschaftlicher_Kongress?.mp4'
'S03E30 - Wer_nicht_fragt,_stirbt_dumm!_-_Was_ist_eigentlich_ein_Blob?.mp4'
'Wer nicht fragt, stirbt dumm!.imdb'
``

**Comment by fracpete** [comment]
I've pushed out a fix. Please install directly from the repo and try again.

**Comment by Chronosaurus42** [comment]
I can confirm now it works as expected, thank you very much

**Comment by fracpete** [comment]
Thanks for confirming. I've pushed out release 0.0.14 with that fix.
